name: Rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install MPI
      run: |
        sudo apt update
        sudo apt install -y mpich

    - uses: Jimver/cuda-toolkit@v0.2.5
      name: Install CUDA
      id: cuda-toolkit
      with:
        cuda: '11.5.1'

    # There seems to be an issue where rustc cannot find libcuda.so.
    #
    # > error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
    #
    # This command fixes that, but it needs more thorough investigation into
    # why this error occurs and what is the right way to fix it.
    - name: Fix libraries
      run: |
          sudo ln -s $CUDA_PATH/lib64/stubs/libcuda.so /usr/lib/libcuda.so
          sudo ln -s $CUDA_PATH/lib64/stubs/libcuda.so /usr/lib/libcuda.so.1


    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, rust-src

    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose --lib
